CREATE TABLE chat
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    ticket_id  BIGINT,
    is_active  BOOLEAN,
    CONSTRAINT pk_chat PRIMARY KEY (id)
);

CREATE TABLE customer
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE,
    updated_at   TIMESTAMP WITHOUT TIME ZONE,
    username     VARCHAR(255)                            NOT NULL,
    password     VARCHAR(255)                            NOT NULL,
    is_enabled   BOOLEAN,
    role         VARCHAR(255),
    first_name   VARCHAR(255),
    last_name    VARCHAR(255),
    phone_number VARCHAR(255),
    CONSTRAINT pk_customer PRIMARY KEY (id)
);

CREATE TABLE customer_feedback
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    ticket_id   BIGINT,
    description VARCHAR(255),
    rating      DOUBLE PRECISION,
    CONSTRAINT pk_customer_feedback PRIMARY KEY (id)
);

CREATE TABLE history
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    role       VARCHAR(255),
    message    VARCHAR(255),
    chat_id    BIGINT,
    agent_id   BIGINT,
    CONSTRAINT pk_history PRIMARY KEY (id)
);

CREATE TABLE invitation
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    username   VARCHAR(255),
    code       VARCHAR(255),
    expire_at  TIMESTAMP WITHOUT TIME ZONE,
    role       VARCHAR(255),
    invited_by BIGINT,
    CONSTRAINT pk_invitation PRIMARY KEY (id)
);

CREATE TABLE refresh_token
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE,
    updated_at    TIMESTAMP WITHOUT TIME ZONE,
    refresh_token VARCHAR(255),
    username      VARCHAR(255),
    expire_at     TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_refresh_token PRIMARY KEY (id)
);

CREATE TABLE ticket_assignment
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at        TIMESTAMP WITHOUT TIME ZONE,
    updated_at        TIMESTAMP WITHOUT TIME ZONE,
    agent_id          BIGINT,
    ticket_id         BIGINT,
    assignment_status VARCHAR(255),
    priority          VARCHAR(255),
    assigned_by       BIGINT,
    is_current_agent  BOOLEAN,
    CONSTRAINT pk_ticket_assignment PRIMARY KEY (id)
);

CREATE TABLE tickets
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE,
    updated_at    TIMESTAMP WITHOUT TIME ZONE,
    description   VARCHAR(255),
    ticket_status VARCHAR(255),
    customer_id   BIGINT,
    CONSTRAINT pk_tickets PRIMARY KEY (id)
);

CREATE TABLE users
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    username   VARCHAR(255)                            NOT NULL,
    password   VARCHAR(255)                            NOT NULL,
    is_enabled BOOLEAN,
    role       VARCHAR(255),
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE customer
    ADD CONSTRAINT uc_customer_username UNIQUE (username);

ALTER TABLE users
    ADD CONSTRAINT uc_users_username UNIQUE (username);

ALTER TABLE chat
    ADD CONSTRAINT FK_CHAT_ON_TICKET FOREIGN KEY (ticket_id) REFERENCES tickets (id);

ALTER TABLE customer_feedback
    ADD CONSTRAINT FK_CUSTOMER_FEEDBACK_ON_TICKET FOREIGN KEY (ticket_id) REFERENCES tickets (id);

ALTER TABLE history
    ADD CONSTRAINT FK_HISTORY_ON_AGENT FOREIGN KEY (agent_id) REFERENCES users (id);

ALTER TABLE history
    ADD CONSTRAINT FK_HISTORY_ON_CHAT FOREIGN KEY (chat_id) REFERENCES chat (id);

ALTER TABLE invitation
    ADD CONSTRAINT FK_INVITATION_ON_INVITED_BY FOREIGN KEY (invited_by) REFERENCES users (id);

ALTER TABLE tickets
    ADD CONSTRAINT FK_TICKETS_ON_CUSTOMER FOREIGN KEY (customer_id) REFERENCES customer (id);

ALTER TABLE ticket_assignment
    ADD CONSTRAINT FK_TICKET_ASSIGNMENT_ON_AGENT FOREIGN KEY (agent_id) REFERENCES users (id);

ALTER TABLE ticket_assignment
    ADD CONSTRAINT FK_TICKET_ASSIGNMENT_ON_ASSIGNED_BY FOREIGN KEY (assigned_by) REFERENCES users (id);

ALTER TABLE ticket_assignment
    ADD CONSTRAINT FK_TICKET_ASSIGNMENT_ON_TICKET FOREIGN KEY (ticket_id) REFERENCES tickets (id);